#ÄÚµå º£³¦
WITH RECURSIVE t AS(
SELECT 0 AS h
    UNION ALL
    SELECT h+1 FROM t WHERE h < 23)
SELECT h, COUNT(HOUR(DATETIME)) AS 'COUNT'
FROM t LEFT OUTER JOIN ANIMAL_OUTS
ON (h=HOUR(DATETIME))
GROUP BY h