#ÄÚµå º£³¦
WITH RECURSIVE TIME AS(
SELECT 0 AS h
    UNION ALL
    SELECT h+1 FROM TIME WHERE h < 23)
SELECT h, COUNT(HOUR(DATETIME)) AS 'COUNT'
FROM TIME LEFT OUTER JOIN ANIMAL_OUTS
ON (h=HOUR(DATETIME))
GROUP BY h