SELECT C.CART_ID FROM CART_PRODUCTS C
LEFT OUTER JOIN CART_PRODUCTS CC ON C.CART_ID = CC.CART_ID
WHERE (C.NAME = 'Yogurt' AND CC.NAME = 'Milk') OR (C.NAME = 'Milk' AND CC.NAME = 'Yogurt')
GROUP BY C.CART_ID